# Trivy configuration for IaC scanning

# Scan configuration
scan:
  security-checks:
    - misconfig  # IaC scanning
    - secret  # Secret detection
    - vuln  # Vulnerability detection
  skip-dirs:
    - .terraform/
    - .terragrunt-cache/
    - .git/

misconfiguration:

  # Same as '--include-non-failures'
  include-non-failures: false

  # Same as '--misconfig-scanners'
  scanners:
   - dockerfile
   - helm
   - kubernetes
   - terraform

  terraform:
    exclude-downloaded-modules: false

# Severity levels to report
severity:
  - CRITICAL
  - HIGH
  - MEDIUM

ignorefile: ".trivyignore"

# Output format
format: table
